# Generated by Django 5.0.2 on 2024-02-23 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='rating',
            new_name='totalprice',
        ),
    ]
