# Generated by Django 5.0.2 on 2024-02-23 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rename_rating_item_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
